# Character property ID's
Properties = {
    0: {"stat": "INVALID", "type": "INVALID", "min": 0, "max": 0, "comment": ""},
    1: {
        "stat": "Strength",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 1000,
        "comment": "STR Attribute",
    },
    2: {
        "stat": "Dexterity",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 1000,
        "comment": "DEX Attribute",
    },
    3: {
        "stat": "Willpower",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 1000,
        "comment": "WIL Attribute",
    },
    4: {
        "stat": "Magic",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 1000,
        "comment": "MAG Attribute",
    },
    5: {
        "stat": "Cunning",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 1000,
        "comment": "CUN Attribute",
    },
    6: {
        "stat": "Constitution",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 1000,
        "comment": "CON Attribute",
    },
    7: {
        "stat": "Health",
        "type": "DEPLETABLE",
        "min": 1,
        "max": 9999,
        "comment": "Hit Points",
    },
    8: {
        "stat": "Mana/Stamina",
        "type": "DEPLETABLE",
        "min": 0,
        "max": 9999,
        "comment": "Mana or Stamina, based on class",
    },
    9: {
        "stat": "Attack",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 1000,
        "comment": "Attack Power",
    },
    10: {
        "stat": "Defense",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 1000,
        "comment": "Defense",
    },
    11: {
        "stat": "Armor",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 1000,
        "comment": "Armor Mitigation Potential",
    },
    12: {
        "stat": "DamageScale",
        "type": "ATTRIBUTE",
        "min": 1,
        "max": 10,
        "comment": "Based Damage Scaling (for difficulty settings and ranks)",
    },
    13: {
        "stat": "SpellPower",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 1000,
        "comment": "Spellpower (Max(MAG-10,0)+Effects)",
    },
    14: {
        "stat": "Regeneration_Health",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 50,
        "comment": "Health Regeneration Rate (Explore Mode) per tick.",
    },
    15: {
        "stat": "Level",
        "type": "SIMPLE",
        "min": 0,
        "max": 99,
        "comment": "Current Character Level.",
    },
    16: {
        "stat": "Displacement",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 100,
        "comment": "Chance to outright evade any physical attach attempt (aka Dodge)",
    },
    17: {
        "stat": "Inventory_Size",
        "type": "SIMPLE",
        "min": 0,
        "max": 1000,
        "comment": "Inventory Slot size (on party)",
    },
    18: {
        "stat": "AI_BEHAVIOR",
        "type": "SIMPLE",
        "min": 0,
        "max": 1000,
        "comment": "Selected AI Behavior",
    },
    19: {
        "stat": "Experience",
        "type": "SIMPLE",
        "min": 0,
        "max": 186001,
        "comment": "Experience Points",
    },
    20: {
        "stat": "Flanking_Angle",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 180,
        "comment": "The angle at which this creature is able to flank an enemy (default is 90)",
    },
    21: {
        "stat": "Melee_Crit_Modifier",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 200,
        "comment": "The +melee crit modifier",
    },
    22: {
        "stat": "Missile_Shield",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 100,
        "comment": "Chance to avoid missiles (shields and some spells increase this)",
    },
    23: {
        "stat": "Ranged_Crit_Modifier",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 200,
        "comment": "The +ranged crit modifier",
    },
    24: {
        "stat": "Ranged_Aim_Speed",
        "type": "ATTRIBUTE",
        "min": -3.0,
        "max": 6.0,
        "comment": "The character's speed bonus or penality when aiming with ranged weapons",
    },
    25: {
        "stat": "BaseAttackRating",
        "type": "SIMPLE",
        "min": 0,
        "max": 1000,
        "comment": "The creature's cached base attack rating",
    },
    26: {
        "stat": "BaseDefenseRating",
        "type": "SIMPLE",
        "min": 0,
        "max": 1000,
        "comment": "The creature's cached base defense rating",
    },
    27: {
        "stat": "CurrentClass",
        "type": "SIMPLE",
        "min": 0,
        "max": 31,
        "comment": "The creature class (index into cla_base.xls)",
    },
    28: {
        "stat": "Regeneration_Health_Combat",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 20,
        "comment": "The creature's health regeneration rate (per tick) in combat.",
    },
    29: {
        "stat": "Regeneration_Stamina",
        "type": "ATTRIBUTE",
        "min": -20,
        "max": 50,
        "comment": "The creature's stamina regeneration rate (per tick) in explore mode.",
    },
    30: {
        "stat": "Regeneration_Stamina_Combat",
        "type": "ATTRIBUTE",
        "min": -20,
        "max": 20,
        "comment": "The creature's stamina regeneration rate (per tick) in combat mode.",
    },
    31: {
        "stat": "AttackSpeedModifier",
        "type": "ATTRIBUTE",
        "min": 0.0,
        "max": 1.5,
        "comment": "The creature's universal melee attack speed modifiers (used by haste, momentum, etc.)",
    },
    32: {
        "stat": "Resistance_Mind",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 100,
        "comment": "Mental Resistance.",
    },
    33: {
        "stat": "Resistance_Physical",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 100,
        "comment": "Physical Resistance.",
    },
    34: {
        "stat": "Attribute_points",
        "type": "SIMPLE",
        "min": 0,
        "max": 100,
        "comment": "Holds any unspent attribute points the creature has. If this is != 0, the UI shows the levelup button.",
    },
    35: {
        "stat": "Skill_points",
        "type": "SIMPLE",
        "min": 0,
        "max": 100,
        "comment": "Holds any unspent skill points the creature has. If this is != 0, the UI shows the levelup button.",
    },
    36: {
        "stat": "talent_spell_points",
        "type": "SIMPLE",
        "min": 0,
        "max": 100,
        "comment": "Holds any unspent talent points the creature has. If this is != 0, the UI shows the levelup button.",
    },
    37: {
        "stat": "Background",
        "type": "SIMPLE",
        "min": 0,
        "max": 10,
        "comment": "The character's origin (index into backgrounds.xls).",
    },
    38: {
        "stat": "specialization_points",
        "type": "SIMPLE",
        "min": 0,
        "max": 2,
        "comment": "Holds any unspent specialization points the creature has.",
    },
    39: {
        "stat": "DamageBonus",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 100,
        "comment": "Universal physical attack damage bonus on the creature.",
    },
    40: {
        "stat": "Threat_Decrease_Rate",
        "type": "SIMPLE",
        "min": -1000,
        "max": 1000,
        "comment": "The rate at which the creature's threat rating decays.",
    },
    41: {
        "stat": "Fatique",
        "type": "ATTRIBUTE",
        "min": -25,
        "max": 250,
        "comment": "The creature's current Fatigue (% increase of ability cost).",
    },
    42: {
        "stat": "Damage_Resistance_Fire",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 75,
        "comment": "The creature's damage resistance to fire. All fire damage is reduce by %.",
    },
    43: {
        "stat": "Damage_Resistance_Cold",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 75,
        "comment": "The creature's damage resistance to cold. All cold damage is reduce by %.",
    },
    44: {
        "stat": "Damage_Resistance_Electricity",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 75,
        "comment": "The creature's damage resistance to lightning. All lightning damage is reduce by %.",
    },
    45: {
        "stat": "Damage_Resistance_Nature",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 75,
        "comment": "The creature's damage resistance to nature. All nature damage is reduce by %.",
    },
    46: {
        "stat": "Damage_Resistance_Spirit",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 75,
        "comment": "The creature's damage resistance to spirit. All spirit damage is reduce by %.",
    },
    47: {
        "stat": "Damage_Shield_points",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 9999,
        "comment": "Magical, damage mitigating shield (all damage types) on the creature. Creature immune to damage until the shield is depleted.",
    },
    48: {
        "stat": "Damage_Shield_strength",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 100,
        "comment": "The maximum amount of damage the creature's magical shields can absorb (not used yet.)",
    },
    49: {
        "stat": "Damage_OffHand",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 9999,
        "comment": "Display only cache of creature's weapon damage potential. This value is only used to marshal data into the UI, it does not have any rules implications.",
    },
    50: {
        "stat": "Damage_MainHand",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 9999,
        "comment": "Display only cache of creature's weapon damage potential. This value is only used to marshal data into the UI, it does not have any rules implications.",
    },
    51: {
        "stat": "Healing_Effect_Factor",
        "type": "ATTRIBUTE",
        "min": 100,
        "max": 200,
        "comment": "Percentage modifier of how effective healing is on the creature. Blood magic does NOT use this field, it is coded in effect_heal_h instead.",
    },
    52: {
        "stat": "Spell_resistance",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 100,
        "comment": "Creature 'hostile magic resistance'. % Chance to avoid any hostile magic.",
    },
    53: {
        "stat": "AP_BONUS",
        "type": "ATTRIBUTE",
        "min": -100,
        "max": 100,
        "comment": "Armor Penetration bonuses  are stored her.",
    },
    54: {
        "stat": "CriticalRange",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 200,
        "comment": "The 'range' which critical hits use. 150 would mean up to 150% of normal damage.",
    },
    55: {
        "stat": "Fire_Damage_Bonus",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 30,
        "comment": "Percentage bonus to all fire damage dealt by the user (spells, staves, etc.)",
    },
    56: {
        "stat": "Spirit_Damage_Bonus",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 30,
        "comment": "Percentage bonus to all spirit damage dealt by the user (spells, staves, etc.)",
    },
    57: {
        "stat": "Cold_Damage_Bonus",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 30,
        "comment": "Percentage bonus to all cold damage dealt by the user (spells, staves, etc.)",
    },
    58: {
        "stat": "Nature_Damage_Bonus",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 30,
        "comment": "Percentage bonus to all nature damage dealt by the user (spells, staves, etc.)",
    },
    59: {
        "stat": "Electricity_Damage_Bonus",
        "type": "ATTRIBUTE",
        "min": 0,
        "max": 30,
        "comment": "Percentage bonus to all lightning damage dealt by the user (spells, staves, etc.)",
    },
    60: {"stat": "Unknown", "type": "INVALID", "min": 0, "max": 0, "comment": "Don't know what that is"},
}